---
- name: Adding repository to get `stable` version.
  apt_repository:
    repo: "ppa:nginx/development"
    state: present

- name: Install nginx.
  apt:
    name: nginx
    state: present
    update_cache: yes
    cache_valid_time: 86400
  notify: restart nginx

- name: Ensure nginx is started and enabled to start on boot.
  service:
    name: nginx
    state: started
    enabled: yes

- name: Adding custom `nginx.conf`
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  when: nginx_add_custom_conf
  notify: reload nginx
